// BREADCRUMBS TYPES
export const ADD_BREADCRUMB = "ADD_BREADCRUMB";
export const SELECT_BREADCRUMB = "SELECT_BREADCRUMB";

// AUTH TYPES
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

// PROFILE TYPES
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_UPDATE_SUCCESS = "CLEAR_UPDATE_SUCCESS";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

// LEAGUE TYPES

export const GET_MANAGER_LEAGUES_LOADING = "GET_MANAGER_LEAGUES_LOADING";
export const GET_MANAGER_LEAGUES_SUCCESS = "GET_MANAGER_LEAGUES_SUCCESS";
export const GET_MANAGER_LEAGUES_FAILED = "GET_MANAGER_LEAGUES_FAILED";

export const GET_LEAGUE_BY_ID_LOADING = "GET_LEAGUE_BY_ID_LOADING";
export const GET_LEAGUE_BY_ID_SUCCESS = "GET_LEAGUE_BY_ID_SUCCESS";
export const GET_LEAGUE_BY_ID_FAILED = "GET_LEAGUE_BY_ID_FAILED";

export const GET_MEMBERS_BY_LEAGUE_ID_LOADING =
  "GET_MEMBERS_BY_LEAGUE_ID_LOADING";
export const GET_MEMBERS_BY_LEAGUE_ID_SUCCESS =
  "GET_MEMBERS_BY_LEAGUE_ID_SUCCESS";
export const GET_MEMBERS_BY_LEAGUE_ID_FAILED =
  "GET_MEMBERS_BY_LEAGUE_ID_FAILED";

export const GET_ROUNDS_BY_LEAGUE_ID_LOADING =
  "GET_ROUNDS_BY_LEAGUE_ID_LOADING";
export const GET_ROUNDS_BY_LEAGUE_ID_SUCCESS =
  "GET_ROUNDS_BY_LEAGUE_ID_SUCCESS";
export const GET_ROUNDS_BY_LEAGUE_ID_FAILED = "GET_ROUNDS_BY_LEAGUE_ID_FAILED";

export const CREATE_NEW_LEAGUE_LOADING = "CREATE_NEW_LEAGUE_LOADING";
export const CREATE_NEW_LEAGUE_SUCCESS = "CREATE_NEW_LEAGUE_SUCCESS";
export const CREATE_NEW_LEAGUE_FAILED = "CREATE_NEW_LEAGUE_FAILED";

export const EDIT_LEAGUE_LOADING = "EDIT_LEAGUE_LOADING";
export const EDIT_LEAGUE_SUCCESS = "EDIT_LEAGUE_SUCCESS";
export const EDIT_LEAGUE_FAILED = "EDIT_LEAGUE_FAILED";

export const ADD_WEEK_TO_SCHEDULE_LOADING = "ADD_WEEK_TO_SCHEDULE_LOADING";
export const ADD_WEEK_TO_SCHEDULE_SUCCESS = "ADD_WEEK_TO_SCHEDULE_SUCCESS";
export const ADD_WEEK_TO_SCHEDULE_FAILED = "ADD_WEEK_TO_SCHEDULE_FAILED";

export const REMOVE_WEEK_FROM_SCHEDULE_LOADING =
  "REMOVE_WEEK_FROM_SCHEDULE_LOADING";
export const REMOVE_WEEK_FROM_SCHEDULE_SUCCESS =
  "REMOVE_WEEK_FROM_SCHEDULE_SUCCESS";
export const REMOVE_WEEK_FROM_SCHEDULE_FAILED =
  "REMOVE_WEEK_FROM_SCHEDULE_FAILED";

export const SUBMIT_SCHEDULE_CHANGES = "SUBMIT_SCHEDULE_CHANGES";

export const UPDATE_SCHEDULE_LOADING = "UPDATE_SCHEDULE_LOADING";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILED = "UPDATE_SCHEDULE_FAILED";

export const CLEAR_LEAGUES = "CLEAR_LEAGUES";
export const CLEAR_LEAGUE_DATA = "CLEAR_LEAGUE_DATA";
