// BREADCRUMBS TYPES
export const ADD_BREADCRUMB = "ADD_BREADCRUMB";
export const SELECT_BREADCRUMB = "SELECT_BREADCRUMB";

// AUTH TYPES
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

// PROFILE TYPES
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_UPDATE_SUCCESS = "CLEAR_UPDATE_SUCCESS";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

// LEAGUE TYPES

export const GET_MANAGER_LEAGUES_LOADING = "GET_MANAGER_LEAGUES_LOADING";
export const GET_MANAGER_LEAGUES_SUCCESS = "GET_MANAGER_LEAGUES_SUCCESS";
export const GET_MANAGER_LEAGUES_FAILED = "GET_MANAGER_LEAGUES_FAILED";

export const GET_LEAGUE_BY_ID_LOADING = "GET_LEAGUE_BY_ID_LOADING";
export const GET_LEAGUE_BY_ID_SUCCESS = "GET_LEAGUE_BY_ID_SUCCESS";
export const GET_LEAGUE_BY_ID_FAILED = "GET_LEAGUE_BY_ID_FAILED";

export const GET_MEMBERS_BY_LEAGUE_ID_LOADING =
  "GET_MEMBERS_BY_LEAGUE_ID_LOADING";
export const GET_MEMBERS_BY_LEAGUE_ID_SUCCESS =
  "GET_MEMBERS_BY_LEAGUE_ID_SUCCESS";
export const GET_MEMBERS_BY_LEAGUE_ID_FAILED =
  "GET_MEMBERS_BY_LEAGUE_ID_FAILED";

export const CLEAR_LEAGUES = "CLEAR_LEAGUES";
